{{- if .Values.vmstorage.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.vmstorage.service.annotations }}
  annotations:
{{ toYaml .Values.vmstorage.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "victoria-metrics.vmstorage.labels" . | nindent 4 }}
{{- if .Values.vmstorage.service.labels }}
{{ toYaml .Values.vmstorage.service.labels | indent 4 }}
{{- end }}
  name: {{ template "victoria-metrics.vmstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.vmstorage.service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.vmstorage.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
    - port: {{ .Values.vmstorage.service.vmselectPort }}
      targetPort: vmselect
      protocol: TCP
      name: vmselect
      {{- with .Values.vmstorage.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
    - port: {{ .Values.vmstorage.service.vminsertPort }}
      targetPort: vminsert
      protocol: TCP
      name: vminsert
      {{- with .Values.vmstorage.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  {{- range .Values.vmstorage.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      {{- with .appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "victoria-metrics.vmstorage.matchLabels" . | nindent 4 }}
{{- end -}}
